FileVersion = 1
Dependencies = {corlib = "*", raylib-beef = "*"}

[Project]
Name = "clay-beef"
TargetType = "BeefLib"
StartupObject = "clay_beef.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/libs/windows/clay.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/libs/windows/*.lib\")"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/libs/windows/clay.lib"]
